name: Assignment 4 - Triggers Demo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Why run this workflow?"
        required: false
        default: "manual trigger"

  schedule:
    - cron: "0 18 * * *"

jobs:
  detect-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: echo "Event: ${{ github.event_name }}"

      - name: On push
        if: ${{ github.event_name == 'push' }}
        run: echo "Triggered by PUSH to main"

      - name: On pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Triggered by a PULL REQUEST"

      - name: On manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Triggered MANUALLY. Reason: ${{ inputs.reason }}"

      - name: On schedule
        if: ${{ github.event_name == 'schedule' }}
        run: echo "Triggered by CRON schedule"
